# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from. import check

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(630, 271)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.comboBox1 = QtGui.QComboBox(self.centralwidget)
        self.comboBox1.setGeometry(QtCore.QRect(140, 30, 211, 31))
        self.comboBox1.setObjectName(_fromUtf8("comboBox1"))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox1.addItem(_fromUtf8(""))
        self.comboBox5 = QtGui.QComboBox(self.centralwidget)
        self.comboBox5.setGeometry(QtCore.QRect(140, 180, 211, 31))
        self.comboBox5.setObjectName(_fromUtf8("comboBox5"))
        self.comboBox5.addItem(_fromUtf8(""))
        self.comboBox5.addItem(_fromUtf8(""))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Bookman L"))
        font.setPointSize(14)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.comboBox2 = QtGui.QComboBox(self.centralwidget)
        self.comboBox2.setGeometry(QtCore.QRect(140, 80, 211, 31))
        self.comboBox2.setObjectName(_fromUtf8("comboBox2"))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.comboBox2.addItem(_fromUtf8(""))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Bookman L"))
        font.setPointSize(14)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.comboBox3 = QtGui.QComboBox(self.centralwidget)
        self.comboBox3.setGeometry(QtCore.QRect(140, 130, 211, 31))
        self.comboBox3.setObjectName(_fromUtf8("comboBox3"))
        self.comboBox3.addItem(_fromUtf8(""))
        self.comboBox3.addItem(_fromUtf8(""))
        self.comboBox3.addItem(_fromUtf8(""))
        self.comboBox3.addItem(_fromUtf8(""))
        self.comboBox3.addItem(_fromUtf8(""))
        self.comboBox3.addItem(_fromUtf8(""))
        self.comboBox3.addItem(_fromUtf8(""))
        self.comboBox3.addItem(_fromUtf8(""))
        self.comboBox3.addItem(_fromUtf8(""))
        self.comboBox3.addItem(_fromUtf8(""))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 111, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Bookman L"))
        font.setPointSize(14)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Bookman L"))
        font.setPointSize(14)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lcdNumber1 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber1.setGeometry(QtCore.QRect(380, 50, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lcdNumber1.setFont(font)
        self.lcdNumber1.setSmallDecimalPoint(False)
        self.lcdNumber1.setNumDigits(8)
        self.lcdNumber1.setObjectName(_fromUtf8("lcdNumber1"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(380, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Serif"))
        font.setPointSize(16)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(590, 50, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(430, 100, 111, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Bookman L"))
        font.setPointSize(10)
        font.setItalic(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lcdNumber2 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber2.setGeometry(QtCore.QRect(380, 130, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lcdNumber2.setFont(font)
        self.lcdNumber2.setSmallDecimalPoint(False)
        self.lcdNumber2.setNumDigits(8)
        self.lcdNumber2.setObjectName(_fromUtf8("lcdNumber2"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(590, 140, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(380, 190, 201, 41))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 630, 19))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuOptions = QtGui.QMenu(self.menuBar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionClear = QtGui.QAction(MainWindow)
        self.actionClear.setObjectName(_fromUtf8("actionClear"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuOptions.addAction(self.actionClear)
        self.menuOptions.addAction(self.actionExit)
        self.menuBar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Resistance Calculator", None))
        self.comboBox1.setItemText(0, _translate("MainWindow", "Black", None))
        self.comboBox1.setItemText(1, _translate("MainWindow", "Brown", None))
        self.comboBox1.setItemText(2, _translate("MainWindow", "Red", None))
        self.comboBox1.setItemText(3, _translate("MainWindow", "Orange", None))
        self.comboBox1.setItemText(4, _translate("MainWindow", "Yellow", None))
        self.comboBox1.setItemText(5, _translate("MainWindow", "Green", None))
        self.comboBox1.setItemText(6, _translate("MainWindow", "Blue", None))
        self.comboBox1.setItemText(7, _translate("MainWindow", "Violet", None))
        self.comboBox1.setItemText(8, _translate("MainWindow", "Grey", None))
        self.comboBox1.setItemText(9, _translate("MainWindow", "White", None))
        comboBox1.activated[str].connect(self.style_choice)

        self.comboBox5.setItemText(0, _translate("MainWindow", "Gold", None))
        self.comboBox5.setItemText(1, _translate("MainWindow", "Silver", None))
        comboBox5.activated[str].connect(self.style_choice)

        self.label.setText(_translate("MainWindow", "First Band", None))

        self.comboBox2.setItemText(0, _translate("MainWindow", "Black", None))
        self.comboBox2.setItemText(1, _translate("MainWindow", "Brown", None))
        self.comboBox2.setItemText(2, _translate("MainWindow", "Red", None))
        self.comboBox2.setItemText(3, _translate("MainWindow", "Orange", None))
        self.comboBox2.setItemText(4, _translate("MainWindow", "Yellow", None))
        self.comboBox2.setItemText(5, _translate("MainWindow", "Green", None))
        self.comboBox2.setItemText(6, _translate("MainWindow", "Blue", None))
        self.comboBox2.setItemText(7, _translate("MainWindow", "Violet", None))
        self.comboBox2.setItemText(8, _translate("MainWindow", "Grey", None))
        self.comboBox2.setItemText(9, _translate("MainWindow", "White", None))
        comboBox2.activated[str].connect(self.style_choice)

        self.label_2.setText(_translate("MainWindow", "Second Band", None))
        comboBox.activated[str].connect(self.style_choice)

        self.comboBox3.setItemText(0, _translate("MainWindow", "Black", None))
        self.comboBox3.setItemText(1, _translate("MainWindow", "Brown", None))
        self.comboBox3.setItemText(2, _translate("MainWindow", "Red", None))
        self.comboBox3.setItemText(3, _translate("MainWindow", "Orange", None))
        self.comboBox3.setItemText(4, _translate("MainWindow", "Yellow", None))
        self.comboBox3.setItemText(5, _translate("MainWindow", "Green", None))
        self.comboBox3.setItemText(6, _translate("MainWindow", "Blue", None))
        self.comboBox3.setItemText(7, _translate("MainWindow", "Violet", None))
        self.comboBox3.setItemText(8, _translate("MainWindow", "Grey", None))
        self.comboBox3.setItemText(9, _translate("MainWindow", "White", None))
        comboBox3.activated[str].connect(self.style_choice)

        self.label_3.setText(_translate("MainWindow", "Third band", None))
        self.label_4.setText(_translate("MainWindow", "Fourth Band", None))
        self.label_6.setText(_translate("MainWindow", "Resistance Value is :", None))
        self.label_7.setText(_translate("MainWindow", " kΩ", None))
        self.label_8.setText(_translate("MainWindow", "Tolerance(+/-) :", None))
        self.label_9.setText(_translate("MainWindow", "%", None))
        self.pushButton.setText(_translate("MainWindow", "Calculate !", None))
        self.menuOptions.setTitle(_translate("MainWindow", "Options", None))
        self.actionClear.setText(_translate("MainWindow", "Clear", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))


        


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
